---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: phpcms
  name: phpcms
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: phpcms

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: phpcms
  labels:
    app: phpcms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpcms
  template:
    metadata:
      labels:
        app: phpcms
    spec:
      containers:
      - name: phpcms
        image: 10.1.2.10:5000/php:latest
        imagePullPolicy: IfNotPresent

